### ISSUE TITLE
Portfolio-mobile menu

### ISSUE THREAD

**Issue by Kayonga99** [Kayonga99/My-Portfolio#16]
## Portfolio mobile menu:
- This milestone was completed and got approved to be merged last week I'm hereby providing the link to the live demo and opened an issue in the portfolio mobile menu branch just as written in the article.
- ### In this milestone the following were implemented:
- No linter errors.
- When the user clicks (or taps) the hamburger button, the mobile menu appears.
- When the user clicks (or taps) the close (X) button, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.

- <a href="https://kayonga99.github.io/My-Portfolio/">Please click here to see live demo</a>

https://github.com/Kayonga99/My-Portfolio/blob/4ec6f89950af3fddf64f501a36942deedce9d698/main.js#L1
https://github.com/Kayonga99/My-Portfolio/blob/4ec6f89950af3fddf64f501a36942deedce9d698/main.js#L2

**Comment by ShoiraTa** [comment]
Hi  👋🏻 ,
While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 😢 

### Invalid Code Review Request

- REASON

- [ ] Please submit a Pull Request, otherwise It is impossible to proceed a proper review. 

 **Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray** 

Cheers and Happy coding! 👏🏻👏🏻 

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear._

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

***

_Invalid Code Review Request Does not count into the code reviews limit._
